list = {
	'float_core.decimal_value_atom(289)': {
		"i":0,
		"o":1,
	},
	'float_core.boolean_value_atom(87)': {
		"i":0,
		"o":1,
	},
	'float_core.integer_value_atom(394)': {
		"i":0,
		"o":1,
	},
	'float_core.indexed_value_atom(180)': {
		"i":0,
		"o":1,
	},
	'float_common_atoms.constant_value_atom(314)': {
		"name":"ConstV",
		"i":0,
		"o":1,
		"w":60,
	},
	'float_common_atoms.constant_integer_value_atom(298)': {
		"name":"ConstI",
		"i":0,
		"o":1,
		"w":60,
	},
	'float_common_atoms.indexed_lookup_table_atom(344)': {
		"name":"LUT",
		"i":1,
		"o":1,
		"w":60,
	},
	'constant_boolean_value_atom(635)': {
		"name":"ConstB",
		"i":0,
		"o":1,
		"w":60,
	},
	
	
	'float_common_atoms.nitro_atom(1721)': {
		"name":"nitro",
		"i":12,
		"o":8,
	},
	'float_common_atoms.mix_atom(301)': {
		"name":"MIX",
		"i":3,
		"o":1,
		"w":30,
		"h":75,
		"vertical":None,
	},
	'float_common_atoms.polyphonic_note_voice_atom(350)': {
		"name":"PolyNoteVoice",
		"i":7,
		"o":10,
		"w":30,
		"vertical":None,
	},
	'float_common_atoms.monophonic_note_voice_atom(402)': {
		"name":"MonoNoteVoice",
		"i":1,
		"o":5,
		"w":30,
		"vertical":None,
	},
	'float_common_atoms.note_delay_compensation_atom(1435)': {
		"i":1,
		"o":1,
		"w":50,
		"h":50,
	},
	'float_common_atoms.delay_compensation_atom(1371)': {
		"i":1,
		"o":1,
		"w":50,
		"h":50,
	},
	'float_core.modulation_source_atom(766)': {
		"i":1,
		"o":0,
	},
	'float_core.value_led_atom(189)': {
		"i":1,
		"o":0,
		"w":30,
		"h":30,
	},
	'float_core.vu_meter_atom(40)': {
		"name":"VUMeter",
		"i":1,
		"o":0,
		"w":30,
		"vertical":None,
	},
	'float_common_atoms.decimal_event_filter_atom(400)': {
		"i":0,
		"o":0,
	},
	'float_common_atoms.multiplexer_atom(1188)': {
		"name":"MUX",
		"i":0,
		"o":0,
		"w":50,
		"h":50,
		"vertical":None,
	},
	'float_common_atoms.stereo_width_atom(297)': {
		"name":"Width",
		"i":2,
		"o":1,
		"w":30,
		"vertical":None,
	},
	'float_core.oscilloscope_atom(1654)': {
		"name":"OScope",
		"i":11,
		"o":1,
		"w":30,
		"vertical":None,
	},
	
	#Math
	'float_common_atoms.constant_add_atom(308)': {
		"name":"+c",
		"i":1,
		"o":1,
		"w":60,
		"h":50, 
	},
	'float_common_atoms.constant_multiply_atom(303)': {
		"name":"*c",
		"i":1,
		"o":1,
		"w":60,
		"h":50, 
	},
	'float_common_atoms.add_atom(337)': {
		"name":"+",
		"i":2,
		"o":1,
		"w":20,
		"h":50,
	},
	'float_common_atoms.multiply_atom(367)': {
		"name":"×",
		"i":2,
		"o":1,
		"w":50,
	},
	'float_common_atoms.subtract_atom(343)': {
		"name":"-",
		"i":2,
		"o":1,
		"w":50,
	},
	'float_common_atoms.tanh_atom(345)': {
		"name":"tanh",
		"i":2,
		"o":1,
		"w":50,
	},
	'float_common_atoms.min_atom(348)': {
		"name":"min",
		"i":2,
		"o":1,
		"w":50,
	},
	'float_common_atoms.max_atom(352)': {
		"name":"max",
		"i":2,
		"o":1,
		"w":50,
	},
	'float_common_atoms.multiply_add_atom(304)': {
		"name":"×+",
		"i":3,
		"o":1,
		"w":50,
	},
	'float_common_atoms.sum_atom(305)': {
		"name":"++",
		"i":0,
		"o":0,
		"w":40,
	},
	
	#Control
	'float_common_atoms.analog_adsr_atom(372)': {
		"name":"AnalogADSR",
		"i":5,
		"o":1,
		"vertical":None,
	},
	
	#DSP
	'float_common_atoms.sample_player_atom(330)': {
		"name":"Sampler",
		"i":6,
		"o":4,
		"vertical":None,
	},
	'float_common_atoms.nested_allpass_filter_atom(336)': {
		"name":"AllPass",
		"i":5,
		"o":1,
		"vertical":None,
	},
	'float_common_atoms.audio_delay_atom(339)': {
		"name":"Delay",
		"i":4,
		"o":1,
		"vertical":None,
	},
	'float_common_atoms.biquad_filter_atom(353)': {
		"name":"BiQ F",
		"i":2,
		"o":1,
		"vertical":None,
	},
	'float_common_atoms.biquad_coefficient_atom(365)': {
		"name":"BiQ C",
		"i":2,
		"o":1,
		"vertical":None,
	},
	'float_common_atoms.surge_classic_oscillator_atom(491)': {
		"name":"SURGE",
		"i":9,
		"o":1,
		"vertical":None,
	},
	'float_common_atoms.feedback_compressor_atom(547)': {
		"name":"Compressor",
		"i":7,
		"o":2,
		"vertical":None,
	},
	'float_common_atoms.svf_filter_atom(578)': {
		"name":"FILTER",
		"i":5,
		"o":1,
		"vertical":None,
	},
	'float_common_atoms.allpass_filter_atom(363)': {
		"name":"ALLPASS",
		"i":3,
		"o":1,
		"vertical":None,
	},
	
	#Components
	'float_core.proxy_in_port_component(154)': {
		"i":0,
		"o":1,
		"w":50,
		"h":50,
	},
	'float_core.proxy_out_port_component(50)': {
		"i":1,
		"o":0,
		"w":50,
		"h":50,
	},
	'float_core.nested_device_chain_slot(587)': {
		"i":2,
		"o":2,
	},
	'float_core.spectrum_analyser_component(1851)': {
		"name":"FFT",
		"i":1,
		"o":0,
		"w":50,
		"h":50,
		"vertical":None,
	},
	'float_common_atoms.audio_switcher_atom(401)': {
		"name":"AudioSW",
		"i":3,
		"o":1,
		"w":30,
		"vertical":None,
	},
	'float_common_atoms.envelope_follower_atom(300)': {
		"name":"Env Follow",
		"i":3,
		"o":1,
		"w":30,
		"vertical":None,
	},
	'float_core.audio_sidechain_routing_component(857)': {
		"name":"SChain",
		"i":1,
		"o":1,
		"w":30,
		"vertical":None,
	},
	'float_common_atoms.gain_detector_atom(545)': {
		"name":"Gain Detect",
		"i":4,
		"o":1,
		"vertical":None,
	},
	'float_common_atoms.domain_converter_atom(320)': {
		"name":"Domain Conv",
		"i":1,
		"o":1,
		"w":75,
	},
	'float_core.gain_change_meter_atom(556)': {
		"name":"Gain Change Meter",
		"i":1,
		"o":0,
		"w":75,
	},
	'float_common_atoms.label_component(374)': {
		"name":"LABEL",
		"i":0,
		"o":0,
		"w":60,
	},
	'float_core.trigger_atom(239)': {
		"name":"Trigger",
		"i":0,
		"o":1,
		"w":60,
	},
	'float_common_atoms.note_trigger_atom(1146)': {
		"name":"Note Trigger",
		"i":1,
		"o":1,
		"w":100,
	},
	'float_common_atoms.step_sequencer_atom(1170)': {
		"name":"Step Sequencer",
		"i":5,
		"o":1,
		"vertical":None,
	},
	
	#converters
	'float_common_atoms.interleave_atom(306)': {
		"name":"LR→S",
		"i":2,
		"o":1,
		"w":60,
		"center":None,
	},
	'float_common_atoms.key_to_frequency_atom(317)': {
		"name":"♩→Hz",
		"i":1,
		"o":1,
		"w":60,
		"center":None,
		#"shape":"hex",
	},
	'float_common_atoms.beattime_to_time_atom(327)': {
		"name":"♪→ms",
		"i":1,
		"o":1,
		"w":60,
		"center":None,
		#"shape":"hex",
	},
	'float_common_atoms.deinterleave_atom(368)': {
		"name":"S→LR",
		"i":1,
		"o":2,
		"w":60,
		"center":None,
	},
	'float_common_atoms.int_to_audio_atom(404)': {
		"name":"int→audio",
		"i":1,
		"o":1,
		"w":60,
		"center":None,
		#"shape":"hex",
	},
	'float_common_atoms.note_event_to_decimal_event_atom(787)': {
		"name":"NE→DE",
		"i":2,
		"o":2,
		"w":60,
		"center":None,
		#"shape":"hex",
	},
	
	'float_common_atoms.event_repeater_atom(414)': {
		"name":"E Repeat",
		"i":3,
		"o":1,
		"vertical":None,
	},
	'float_common_atoms.velocity_amp_multiplier_atom(471)': {
		"name":"Velocity",
		"i":3,
		"o":1,
		"vertical":None,
	},
	'float_common_atoms.held_impulse_atom(405)': {
		"name":"HeldImpulse",
		"i":2,
		"o":1,
		"vertical":None,
	},
	'float_common_atoms.exponential_decay_atom(398)': {
		"name":"exp Decay",
		"i":3,
		"o":1,
		"vertical":None,
	},
	'float_common_atoms.amp_and_pan_atom(431)': {
		"name":"Amp&Pan",
		"i":3,
		"o":1,
		"vertical":None,
	},
	'float_common_atoms.moving_average_filter_atom(565)': {
		"name":"AvgFilt",
		"i":1,
		"o":1,
		"w":60,
	},
	'float_common_atoms.buffer_reader_atom(331)': {
		"name":"Read",
		"i":1,
		"o":1,
		"w":60,
	},
	'float_common_atoms.buffer_writer_atom(364)': {
		"name":"Write",
		"i":1,
		"o":0,
		"w":60,
	},
	'float_common_atoms.sine_resonator_atom(413)': {
		"name":"SineReso",
		"i":3,
		"o":1,
		"vertical":None,
	},
	'float_common_atoms.bend_curve_atom(542)': {
		"name":"BendCurve",
		"i":2,
		"o":1,
		"vertical":None,
	},
	'float_common_atoms.vibrato_delaytime_modulation_atom(412)': {
		"name":"D-Vibrato",
		"i":2,
		"o":1,
		"vertical":None,
	},
	'float_common_atoms.audio_voice_combiner_atom(313)': {
		"name":"Combine",
		"i":3,
		"o":1,
		"vertical":None,
	},
	'float_core.polyphonic_observer_atom(1815)': {
		"name":"PolyObs",
		"i":2,
		"o":1,
		"vertical":None,
	},
	'last_voice_int_event_atom(2076)': {
		"name":"LVint",
		"i":1,
		"o":1,
		"w":80,
	},
	'last_voice_audio_atom(2077)': {
		"name":"LastVoice",
		"i":1,
		"o":1,
		"w":80,
	},
	'lightweight_oscilloscope_atom(2072)': {
		"name":"OScope(L)",
		"i":4,
		"o":0,
		"vertical":None,
	},
}
