list = {
	'float_core.decimal_value_atom(289)': {
		"i":1,
		"o":1,
	},
	'float_core.boolean_value_atom(87)': {
		"i":1,
		"o":1,
	},
	'float_core.integer_value_atom(394)': {
		"i":1,
		"o":1,
	},
	'float_core.indexed_value_atom(180)': {
		"i":1,
		"o":1,
	},
	'float_common_atoms.constant_value_atom(314)': {
		"i":0,
		"o":1,
		"w":60,
	},
	'float_common_atoms.constant_integer_value_atom(298)': {
		"i":0,
		"o":1,
		"w":60,
	},
	'float_common_atoms.nitro_atom(1721)': {
		"i":12,
		"o":8,
	},
	'float_common_atoms.mix_atom(301)': {
		"i":3,
		"o":1,
		"w":30,
		"h":75,
	},
	'float_common_atoms.polyphonic_note_voice_atom(350)': {
		"i":7,
		"o":10,
		"w":30,
	},
	'float_common_atoms.note_delay_compensation_atom(1435)': {
		"i":1,
		"o":1,
		"w":50,
		"h":50,
	},
	'float_common_atoms.delay_compensation_atom(1371)': {
		"i":1,
		"o":1,
		"w":50,
		"h":50,
	},
	'float_core.modulation_source_atom(766)': {
		"i":1,
		"o":0,
	},
	'float_core.value_led_atom(189)': {
		"i":1,
		"o":0,
		"w":30,
		"h":30,
	},
	'float_core.vu_meter_atom(40)': {
		"i":1,
		"o":0,
		"w":65,
		"h":50,
	},
	'float_common_atoms.decimal_event_filter_atom(400)': {
		"i":0,
		"o":0,
	},
	'float_common_atoms.multiplexer_atom(1188)': {
		"i":0,
		"o":0,
		"w":50,
		"h":50,
	},
	'float_common_atoms.deinterleave_atom(368)': {
		"i":1,
		"o":2,
		"w":30,
		"h":50,
	},
	'float_common_atoms.indexed_lookup_table_atom(344)': {
		"i":1,
		"o":1,
	},
	'float_common_atoms.stereo_width_atom(297)': {
		"i":1,
		"o":1,
		"w":75,
		"h":50,
	},
	'float_core.oscilloscope_atom(1654)': {
		"i":10,
		"o":1,
		"w":30,
		"h":180,
	},
	'float_common_atoms.constant_add_atom(308)': {
		"i":1,
		"o":1,
		"w":50,
		"h":50, 
	},
	'float_common_atoms.constant_multiply_atom(303)': {
		"i":1,
		"o":1,
		"w":50,
		"h":50, 
	},
	'float_common_atoms.add_atom(337)': {
		"i":2,
		"o":1,
		"w":20,
		"h":50,
	},
	'float_common_atoms.multiply_atom(367)': {
		"i":2,
		"o":1,
		"w":20,
		"h":50,
	},
	'float_common_atoms.subtract_atom(343)': {
		"i":2,
		"o":1,
		"w":20,
		"h":50,
	},
	'float_common_atoms.tanh_atom(345)': {
		"i":2,
		"o":1,
		"w":30,
		"h":50,
	},
	'float_common_atoms.min_atom(348)': {
		"i":2,
		"o":1,
		"w":30,
		"h":50,
	},
	'float_common_atoms.max_atom(352)': {
		"i":2,
		"o":1,
		"w":30,
		"h":50,
	},
	'float_common_atoms.multiply_add_atom(304)': {
		"i":3,
		"o":1,
		"w":30,
		"h":50,
	},
	'float_common_atoms.sum_atom(305)': {
		"i":0,
		"o":0,
		"w":30,
		"h":50,
	},
	'float_common_atoms.svf_filter_atom(578)': {
		"i":5,
		"o":1,
		"w":25,
		"h":100,
	},
	'float_common_atoms.surge_classic_oscillator_atom(491)': {
		"i":9,
		"o":1,
		"w":30,
		"h":160,
	},
	'float_core.proxy_in_port_component(154)': {
		"i":0,
		"o":1,
		"w":75,
		"h":50,
	},
	'float_core.proxy_out_port_component(50)': {
		"i":1,
		"o":0,
		"w":75,
		"h":50,
	},
	'float_core.nested_device_chain_slot(587)': {
		"i":2,
		"o":2,
	},
	'float_core.spectrum_analyser_component(1851)': {
		"i":1,
		"o":0,
		"w":50,
		"h":50,
	},
	'float_common_atoms.audio_switcher_atom(401)': {
		"i":3,
		"o":1,
		"w":50,
		"h":50,
	},
	'float_common_atoms.envelope_follower_atom(300)': {
		"i":3,
		"o":1,
		"w":50,
		"h":50,
	},
	'float_core.audio_sidechain_routing_component(857)': {
		"i":1,
		"o":1,
		"w":30,
		"h":75,
	},
}
